version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: local
            APP_KEY: base64:2Yom9Lvu0C3INq3Xiu4g0zitnOpYeE7NBitYXSWfF8I=
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: refer-earn-app
            DB_USERNAME: root
            DB_PASSWORD:
